---
title: "Lab 10 Intro"
date: "`r Sys.Date()`"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library("jpeg")
```

## Seating & Set-up
1. Please make sure that you sit next to your group members for the rest of the quarter.
2. Please set-up your computer as normal.

## Warm-up
1. Please load the homerange data `Tamburelloetal_HomeRangeDatabase.csv`
2. Show the min, mean, and max log10.mass by taxonomic class in the dataset.
3. Make a plot that best summarizes this output.
```{r}
library(tidyverse)
library(here)
library(janitor)
library(naniar)
```


```{r}
homerange <- read.csv("data/Tamburelloetal_HomeRangeDatabase.csv")
homerange
```
```{r}
homerange %>% 
  group_by(class) %>% 
  summarize(mean_log10.mass= mean(log10.mass),
            med_log10.mass = median(log10.mass),
            min_log10.mass = min(log10.mass),
            max_log10.mass = max(log10.mass))
  
```
```{r}
homerange %>% 
  ggplot(aes(x = class, y = log10.mass))+geom_boxplot()
```
```{r}
fish <- homerange %>% 
  filter(class == "actinopterygii")
```

